#-------------基层-------------
[common]
company_name = "公司名字"

[linked]
customer_qq = 2437423541
contact_email = "jiangzhigguo@163.com"
official_weibo = "鱼笙App"

[gateway]
enable = true
port = 30011
log_level = 1

#-------------服务器配置-------------
[server]
http_domain = ""
http_port = "30011"
#http_port = 30012
log_level = 1
