############################################# 模块 #############################################

name = "基层api"
enable = false
cloud = true
prod = true

[client]
name = "client"
enable = true
prod = false

[user]
name = "user"
enable = true
prod = false

[account]
name = "account"
enable = true
prod = false
