############################################# 模块 #############################################

[module]
enable = false
cloud = true
prod = true

[module.client]
enable = true
prod = true

[module.user]
enable = true
prod = false

[module.account]
enable = true
prod = false
